import test from 'node:test';
import assert from 'node:assert/strict';
import {createInvestigator} from '../server/services/investigation.js';
function fixture({mismatch=false,denied=false,graphFail=false,dnsFail=false,delivery='unknown'}={}){
 const calls=[],events=[];
 const investigate=createInvestigator({domainService:{getDomainDetail:()=>denied?{error:{status:404,code:'not_found',message:'missing'}}:{domain:{name:'example.test',kind:'custom'},mailboxes:[{address:'hello@example.test'}]},inspectDomain:async args=>{calls.push(['dns',args]);if(dnsFail)throw Error('SECRET');return {ok:true,checks:['ownership','mx','spf','dkim','dmarc'].map(scope=>({scope,status:mismatch&&scope==='dkim'?'warn':'pass'})),delivery:{inbound:delivery,outbound:delivery}};}},graph:{getDomainGraph:async(...args)=>{calls.push(['graph',args]);if(graphFail)throw Error('SECRET');return {nodes:[{id:'d',type:'Domain',tenantId:'t'},{id:'other',type:'Mailbox',address:'other@example.test',tenantId:'other'}],edges:[]};},blockers:async(...args)=>{calls.push(['blockers',args]);return [{recordId:'r',scope:'dkim'}];},impact:async(...args)=>{calls.push(['impact',args]);return [{address:'hello@example.test'},{address:'other@example.test'}];}}});
 return {run:(signal)=>investigate({tenantId:'t',domainId:'d',onEvent:e=>events.push(e),signal}),calls,events};
}
test('passing DNS skips repair tools, but never equates configuration with delivery',async()=>{const f=fixture();const r=await f.run();assert.equal(r.outcome,'unverified');assert.deepEqual(f.calls.map(c=>c[0]),['dns','graph']);assert.equal(f.calls[0][1].persist,false);assert.ok(r.steps.some(s=>s.id==='decision'));assert.equal(r.graph.nodes.length,1);assert.ok(f.events.some(e=>e.step.status==='running'));assert.ok(r.steps.every(s=>s.status!=='running'));});
test('failed DNS selects graph impact tools and returns only owned addresses',async()=>{const f=fixture({mismatch:true});const r=await f.run();assert.equal(r.outcome,'attention');assert.deepEqual(r.affectedMailboxes,['hello@example.test']);assert.deepEqual(f.calls.map(c=>c[0]),['dns','graph','blockers','impact']);assert.deepEqual(f.calls.find(c=>c[0]==='impact')[1],['t','r']);});
test('access denial produces no stream events and no provider calls',async()=>{const f=fixture({denied:true});const r=await f.run();assert.equal(r.ok,false);assert.equal(f.calls.length,0);assert.equal(f.events.length,0);});
test('graph failure is visible and cannot produce a verified outcome',async()=>{const f=fixture({graphFail:true,delivery:'pass'});const r=await f.run();assert.equal(r.outcome,'attention');assert.equal(r.graphSource,'unavailable');assert.equal(r.graph,null);assert.ok(!JSON.stringify(r).includes('SECRET'));});
test('DNS failure remains unknown, not a completed successful check',async()=>{const f=fixture({dnsFail:true});const r=await f.run();assert.equal(r.outcome,'attention');assert.equal(r.steps.find(s=>s.id==='dns').status,'error');assert.equal(r.delivery.inbound,'unknown');assert.equal(r.checks.length,0);});
test('aborted investigation performs no tools',async()=>{const f=fixture();const c=new AbortController();c.abort();await assert.rejects(f.run(c.signal),/cancelled/);assert.equal(f.calls.length,0);});
test('only complete passing evidence allows verified status',async()=>{const f=fixture({delivery:'pass'});assert.equal((await f.run()).outcome,'verified');});
